[project]
name = "resorter-py"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "click>=8.1.8",
    "pandas>=2.2.3",
    "scipy>=1.15.1",
]

[tool.uv]
dev-dependencies = [
    "pytest>=8.3.4",
]
